// export const SET_ALERT = "SET_ALERT";
// export const REMOVE_ALERT = "REMOVE_ALERT";
// export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
// export const REGISTER_FAIL = "REGISTER_FAIL";
// export const USER_LOADED = "USER_LOADED";
// export const AUTH_ERROR = "AUTH_ERROR";
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_FAIL = "LOGIN_FAIL";
// export const LOGOUT = "LOGOUT";
// export const CLEAR_ERRORS = "CLEAR_ERRORS";

// PUBLIC
export const GET_SERVICES_AND_CATEGORIES = "GET_SERVICES_AND_CATEGORIES";
export const PUBLIC_ERROR = "PUBLIC_ERROR";
export const SET_PUBLIC_LOADING = "SET_PUBLIC_LOADING";
export const ADD_TO_CART = "ADD_TO_CART";
export const SET_CART = "SET_CART";

// AUTH
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const  USER_UPDATED_SELF = " USER_UPDATED_SELF";
// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// USER---------------------------------------------
export const USER_ORDER_FORM_SUBMITTED = "USER_ORDER_FORM_SUBMITTED";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const USER_ORDERS_LOADED = "USER_ORDERS_LOADED";

export const SET_SINGLE_ORDER = "SET_SINGLE_ORDER";


// ADMIN--------------------------------------------
// Loading
export const SET_ADMIN_LOADING = "SET_ADMIN_LOADING";

// Products 
export const PRODUCT_ADDED = "PRODUCT_ADDED";
export const PRODUCTS_INFO_LOADED = "PRODUCTS_INFO_LOADED";
export const QUERIED_PRODUCTS_LOADED = "QUERIED_PRODUCTS_LOADED";
export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";

// CATEGORIES
export const CATEGORY_ADDED = "CATEGORY_ADDED";
export const CATEGORIES_LOADED = "CATEGORIES_LOADED";
export const CATEGORY_DELETED = "CATEGORY_DELETED";

// Services
export const SINGLE_SERVICE_LOADED = "SINGLE_SERVICE_LOADED";
export const SERVICE_ADDED = "SERVICE_ADDED";
export const SERVICE_UPDATED = "SERVICE_UPDATED";
export const SERVICE_DELETED = "SERVICE_DELETED";
export const SERVICES_LOADED = "SERVICES_LOADED";
export const QUERIED_SERVICES_LOADED = "QUERIED_SERVICES_LOADED";
export const CLEAR_QUERIED_SERVICES = "CLEAR_QUERIED_SERVICES";

// Orders
export const ORDER_FORM_SUBMITTED = "ORDER_FORM_SUBMITTED";
export const SINGLE_ORDER_LOADED = "SINGLE_ORDER_LOADED";
export const ORDER_FORM_UPDATED = "ORDER_FORM_UPDATED";
export const ORDERS_LOADED = "ORDERS_LOADED";

// User Activities
export const PAYMENTS_LOADED = "PAYMENTS_LOADED";

// Customers

export const CUSTOMER_ADDED = "CUSTOMER_ADDED";
export const CUSTOMER_UPDATED = "CUSTOMER_UPDATED";
export const CUSTOMER_DELETED = "CUSTOMER_DELETED";
export const CUSTOMERS_LOADED = "CUSTOMERS_LOADED";
export const CLEAR_QUERIED_USERS = "CLEAR_QUERIED_USERS";

// Service Status
export const SERVICE_STATUSES_LOADED = "SERVICE_STATUSES_LOADED";




 
